// Generated by CoffeeScript 1.3.3
(function() {
  var createObject, get_random_color,
    _this = this;

  $(function() {
    var meeting, zebra;
    FlashMessage.target($("#flash"));
    zebra = new Zebra("col_1", Obj);
    meeting = new Meeting(Obj, "col_1", "col_2");
    Obj.loadAll();
    return $("#add_object").asEventStream("click").onValue(function() {
      return createObject("col_1");
    });
  });

  createObject = function(block) {
    var color, height, left, obj, top, width;
    color = get_random_color();
    top = Math.round(Math.random() * (window.innerHeight - 100));
    left = Math.round(Math.random() * ($("#" + block).width() - 200));
    height = Math.round(Math.random() * (window.innerHeight - top) / 2) + 30;
    width = Math.round(Math.random() * ($("#" + block).width() - left) / 3) + 60;
    return obj = new Obj(block, null, left, top, width, height, color);
  };

  get_random_color = function() {
    var color, i, letters, _i;
    letters = '0123456789ABCDEF'.split('');
    color = '#';
    for (i = _i = 0; _i <= 5; i = ++_i) {
      color += letters[Math.floor(Math.random() * 16)];
    }
    return color;
  };

}).call(this);
